defaults:
  - ctrl_eval
  - /env@runner.env: variable_viperx
  - override /runner@runner: mink
  - _self_

runner:
  env:
    pickle_path: ???

hardware_traj_pairs_generator:
  _partial_: true
  _target_: t2.eval.ctrl.identity
  _args_:
    # traj 0
    - [126, 0]
    - [343, 0]
    - [594, 0]
    - [825, 0]
    - [232, 0]

    # traj 1
    - [126, 1]
    - [343, 1]
    - [825, 1]
    - [449, 1]
    - [525, 1]

    # traj 2
    - [126, 2]
    - [594, 2]
    - [839, 2]
    - [343, 2]
    - [232, 2]

    # traj 3
    - [126, 3]
    - [343, 3]
    - [825, 3]
    - [594, 3]
    - [232, 3]

    # traj 4
    - [126, 4]
    - [449, 4]
    - [594, 4]
    - [825, 4]
    - [232, 4]

    # traj 5
    - [343, 5]
    - [126, 5]
    - [825, 5]
    - [232, 5]
    - [821, 5]

    # traj 6
    - [126, 6]
    - [343, 6]
    - [839, 6]
    - [232, 6]
    - [594, 6]

    # traj 7
    - [126, 7]
    - [343, 7]
    - [825, 7]
    - [821, 7]
    - [232, 7]

    # traj 8
    - [126, 8]
    - [839, 8]
    - [594, 8]
    - [343, 8]
    - [825, 8]

    # traj 9
    - [343, 9]
    - [821, 9]
    - [825, 9]
    - [232, 9]
    - [525, 9]

    # traj 10
    - [126, 10]
    - [839, 10]
    - [594, 10]
    - [343, 10]
    - [232, 10]

    # traj 11
    - [126, 11]
    - [449, 11]
    - [825, 11]
    - [232, 11]
    - [525, 11]

    # traj 12
    - [343, 12]
    - [232, 12]
    - [825, 12]
    - [525, 12]
    - [449, 12]

    # traj 13
    - [126, 13]
    - [343, 13]
    - [825, 13]
    - [839, 13]
    - [525, 13]

    # traj 14
    - [343, 14]
    - [825, 14]
    - [821, 14]
    - [232, 14]
    - [525, 14]

    # traj 15
    - [594, 15]
    - [343, 15]
    - [839, 15]
    - [825, 15]
    - [232, 15]

    # traj 16
    - [126, 16]
    - [343, 16]
    - [825, 16]
    - [821, 16]
    - [232, 16]

    # traj 17
    - [126, 17]
    - [594, 17]
    - [449, 17]
    - [825, 17]
    - [232, 17]

    # traj 18
    - [343, 18]
    - [821, 18]
    - [825, 18]
    - [839, 18]
    - [232, 18]

    # traj 19
    - [126, 19]
    - [343, 19]
    - [839, 19]
    - [825, 19]
    - [232, 19]
