_target_: t2.env.track_env.TrackEnv
# make sure this matches `look_ahead_steps` in the runner config
pickle_path: ???
episode_len: 2000
sim_dt: 0.002
ctrl_dt: 0.02
robot_generator:
  _target_: t2.robogen.wheeled_bimanual.wheeled_bimanual
  _partial_: true
n_end_effectors: 2
pos_noise: 0.0
orn_noise: 0.0
scale_noise: 0.0
noise_sample_prob: 0.0
remove_visual_asset: false
pos_err_sigma: 0.01
orn_err_sigma: 0.5
termination_fellover_threshold: null # disable fellover termination
obs_time_indices: [0]
include_obs_time_indices: none
termination_pos_err_threshold: 0.5
center_traj: true
add_plane: true
max_vis_actuator_force: 100.0
gravcomp: true
