defaults:
  - dataset@datasets.ctrl_rand.dataset: base
  - model/tasks@model.tasks.ctrl: memoryless_nofreelink_ctrl
  # - override env@evals.ctrl.runner.env: variable_viperx
  - override dataset/timestep_sampler@datasets.ctrl_rand.dataset.timestep_sampler: forward
  - override model/tasks/adapter@model.tasks.ctrl.adapters.link: link_log
  - override model/tasks/adapter@model.tasks.ctrl.adapters.dyna_joint: dyna_joint_log
  - override model/tasks/adapter@model.tasks.ctrl.adapters.actuator: actuator_log
  - _self_

ctrl_dataset_path: ???

ctrl_pos_id_seq_lens: &ctrl_pos_id_seq_lens
  dyna_joint:
    - ${eval:"int(${ctrl_seq_len.dyna_joint}//2)"}
    - 0
    - 1
    - 2
  fixed_joint:
    - ${eval:"int(${ctrl_seq_len.fixed_joint}//2)"}
    - 0
    - 1
    - 2
  link:
    - ${ctrl_seq_len.link}
    - 0
    - 1
    - 1
  actuator:
    - ${ctrl_seq_len.actuator}
    - 0
    - 1
    - 1
  # all obs are scaled by rollout_steps
  track_link_obs/track_link:
    - ${ctrl_seq_len.track_link}
    - 0
    - ${ctrl_seq_len.rollout_steps}
    - 1
  dyna_joint_obs/dyna_joint:
    - ${ctrl_seq_len.dyna_joint_obs}
    - 0
    - ${ctrl_seq_len.rollout_steps}
    - 1
  actuator_obs/actuator:
    - ${ctrl_seq_len.actuator_obs}
    - 0
    - ${ctrl_seq_len.rollout_steps}
    - 1
  ctrl/actuator:
    - ${ctrl_seq_len.actuator}
    - 0
    - ${ctrl_seq_len.rollout_steps}
    - 1
  target_pose/track_link:
    - ${ctrl_seq_len.track_link}
    - 0
    - ${ctrl_seq_len.rollout_steps}
    - 1

datasets:
  ctrl_rand:
    batch_size: ${train.batch_size}
    dataset:
      group_time_offsets:
        target_pose: 4
      path: ${ctrl_dataset_path}
      group_seq_lens: ${ctrl_seq_len}
      timestep_sampler:
        num_rollout_steps: ${ctrl_seq_len.rollout_steps}
      rollout_groups:
        - ctrl
        - track_link_obs
        - dyna_joint_obs
        # - free_link_obs # fixed based arms don't have free link obs
        - actuator_obs
        - target_pose
    tasks:
      - ctrl
      # - hardware_gen # maybe it also helps?
    batch_process_fn:
      _target_: t2.train.augment.ComposeAugmentation
      augmentations:
        - _target_: t2.train.augment.AddPositionId
          pos_seq_lens:
            <<: *ctrl_pos_id_seq_lens
        - _target_: t2.train.augment.AddJointOrderAugmentation
        # - _target_: t2.train.augment.TransformAugmentation
        #   pos_aug_magnitude: [0.3, 0.3, 0.0]
        #   orn_aug_magnitude: [0.0, 0.0, 0.5]
        #   affected_pose_fields:
        #     - target_pose
        #     # - free_link_obs # fixed based arms don't have free link obs
        #     - track_link_obs
        #
# evals:
#   ctrl:
#     runner:
#       render: false
#     policy_server_kwargs:
#       batch_size: 20
#       batch_process_fn:
#         _target_: t2.train.augment.AddPositionId
#         pos_seq_lens:
#           <<: *ctrl_pos_id_seq_lens

# ViperX design-space token counts
seq_len:
  dyna_joint: 14
  free_link: 1
  fixed_joint: 22
  link: 18
  actuator: 7
  track_link: 1
