defaults:
  - runner: bimanual_mink
  - env@runner.env: viperx_upside_down_bimanual_50cm
  - override hydra/job_logging: custom
  - _self_

runner:
  env:
    pickle_path: ???
  render: true
  render_fps: 30
  log_dir: renders

episode_seed: 0
num_episodes_per_hardware: 1

hardware_seeds: [0]
num_hardware: 1

num_processes: 1
num_gpus_per_worker: 0

data_path: ???
randomized_episode_seeds: false
