defaults:
  - env: mjx_umi_on_legs
  - env@eval_env: mjx_umi_on_legs_eval
  - _self_
  - override hydra/job_logging: custom

wandb:
  tags: null

eval_envs:
  obs_time_indices: ${env.obs_time_indices}
  terminate_on_bad_contact: false
  termination_fellover_threshold: 0.1
env:
  terminate_on_bad_contact: true
  termination_fellover_threshold: 0.5

seed: 0
render_on_checkpoint: false
full_reset: true
observe_domain_randomized_attrs: true
arm_mount_pos:
- [-0.2,0.0,0.094]
- [0.2,0.0,0.15]
arm_mount_euler:
 - [0.0,0.0,0.0]
 - [0.0,0.0,0.0]

train:
  _convert_: all
  _target_: t2.mjx_env.train.train
  num_timesteps: 400000000
  num_evals: 10
  num_eval_envs: 100
  reward_scaling: 1.0
  clipping_epsilon: 0.2
  episode_length: ${env.max_episode_length}
  normalize_observations: true
  action_repeat: 1
  unroll_length: 24
  num_minibatches: 4
  num_updates_per_batch: 8
  discounting: 0.99
  learning_rate: 1e-3
  entropy_cost: 1e-2
  gae_lambda: 0.95
  num_envs: 4096
  batch_size: 1024
  max_grad_norm: 1.0
  deterministic_eval: true
  log_training_metrics: false
  training_metrics_steps: null
  seed: ${seed}
  network_factory:
    _partial_: true
    _target_: brax.training.agents.ppo.networks.make_ppo_networks
    state_dependent_std: false
    init_noise_std: 1.0
    noise_std_type: scalar
    distribution_type: normal
    activation:
      # _target_: flax.linen.swish
      _target_: flax.linen.elu
      _partial_: true
    policy_hidden_layer_sizes:
      - 256
      - 128
      - 64
    value_hidden_layer_sizes:
      - 256
      - 128
      - 64
